variable "prefix" {
  type        = string
  description = "Prefix to add to the resources"
}

variable "sqs_name" {
  type        = string
  description = "The name of the SQS Queue"
}

variable "sns_topic_name" {
  type        = string
  description = "The name of the SNS topic to subscribe to"
}

variable "sns_topic_arn" {
  type        = string
  description = "The ARN of the SNS topic to subscribe to"
}

variable "tags" {
  type        = map(string)
  description = "Tags to apply to the resources generated by this module"
}

locals {
  tags = merge(var.tags, {
    "Source" = "Terraform"
    "Module" = "sqs-subscriber"
  })
  sns_topic_parts = split(":", var.sns_topic_arn)
  region          = local.sns_topic_parts[3]
  account_id      = local.sns_topic_parts[4]
  queue_name      = "${var.prefix}-${var.sqs_name}"
  queue_arn       = format("arn:aws:sqs:%s:%s:%s", local.region, local.account_id, local.queue_name)
}